version: '2'

services:

  # https://github.com/tozd/docker-postfix/blob/master/run.sh
  # docker run --detach=true --restart=always --name "${NAME}" --hostname "${MAILNAME}" --env MAILNAME --env MY_NETWORKS --env ROOT_ALIAS --env MY_DESTINATION --volume "${POSTFIX_LOG}:/var/log/postfix" --volume "${POSTFIX_DATA}:/var/spool/postfix" tozd/postfix
  postfix:
    image: tozd/postfix
    container_name: postfix
    hostname: ${smtp_hostname}
    environment:
      MAILNAME: ${MAILNAME}
      MY_NETWORKS: ${MY_NETWORKS}
      ROOT_ALIAS: ${ROOT_ALIAS}
      MY_DESTINATION: ${MY_DESTINATION}"localhost.localdomain, localhost"
    ports:
      - "${ext_smtp_port}:25"
    volumes:
      - "${POSTFIX_VOL}_LOG:/var/log/postfix"
      - "${POSTFIX_VOL}_DATA:/var/spool/postfix"
    volume_driver: ${volume_driver}
