version: '2'
volumes:
  gitlab-app-data:
    driver: ${volumedriver}
    driver_opts:
      exportBase: /opt/share/gitlab
  gitlab-log-data:
    driver: ${volumedriver}
    driver_opts:
      exportBase: /opt/share/gitlab
  gitlab-conf-files:
    driver: ${volumedriver}
    driver_opts:
      exportBase: /opt/share/gitlab

services:
  gitlab-server:
    restart: always
    ports:
      - ${ssh_port}:22/tcp
      - ${http_port}:80/tcp
      - ${https_port}:443/tcp
    labels:
      io.rancher.container.hostname_override: container_name
    image: "gitlab/gitlab-ce:11.11.5-ce.0"
    volumes:
      - gitlab-app-data:/var/opt/gitlab
      - gitlab-log-data:/var/log/gitlab
      - gitlab-conf-files:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${ssh_port}

    # volumes:
    #   - ${gitlab_store}/data:/var/opt/gitlab
    #   - ${gitlab_store}/logs:/var/log/gitlab
    #   - ${gitlab_store}/config:/etc/gitlab
    # volume_driver: ${volume_driver}
    # environment:
    #   GITLAB_ROOT_PASSWORD: "${gitlab_root_psw}"
      # GITLAB_OMNIBUS_CONFIG: |
      #   external_url '${gitlab_external_url}'
      #   gitlab_rails['gitlab_shell_ssh_port'] = ${gitlab_ssh_port}

  # gitlab-runner:
  #   image: gitlab/gitlab-runner:alpine


# https://docs.gitlab.com/omnibus/docker/
# sudo docker run --detach \
#   --hostname gitlab.example.com \
#   --publish 443:443 --publish 80:80 --publish 22:22 \
#   --name gitlab \
#   --restart always \
#   --volume /srv/gitlab/config:/etc/gitlab \
#   --volume /srv/gitlab/logs:/var/log/gitlab \
#   --volume /srv/gitlab/data:/var/opt/gitlab \
#   gitlab/gitlab-ce:latest
# https://qiita.com/Mr-K/items/e0d8f905946703767954
