# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  gitlab-ce:
    image: gitlab/gitlab-ce:latest
    # hostname: "${gitlab_host_name}"
    restart: always
    ports:
      - "61022:22"
      - "61080:80"
      - "61443:443"
      # - "${gitlab_ssh_port}:22"
      # - "${gitlab_http_port}:80"
      # - "${gitlab_https_port}:443"
    # volumes:
    #   - ${gitlab_store}/data:/var/opt/gitlab
    #   - ${gitlab_store}/logs:/var/log/gitlab
    #   - ${gitlab_store}/config:/etc/gitlab
    # volume_driver: ${volume_driver}
    # environment:
    #   GITLAB_ROOT_PASSWORD: "${gitlab_root_psw}"
      # GITLAB_OMNIBUS_CONFIG: |
      #   external_url '${gitlab_external_url}'
      #   gitlab_rails['gitlab_shell_ssh_port'] = ${gitlab_ssh_port}

  # gitlab-runner:
  #   image: gitlab/gitlab-runner:alpine


# https://docs.gitlab.com/omnibus/docker/
# sudo docker run --detach \
#   --hostname gitlab.example.com \
#   --publish 443:443 --publish 80:80 --publish 22:22 \
#   --name gitlab \
#   --restart always \
#   --volume /srv/gitlab/config:/etc/gitlab \
#   --volume /srv/gitlab/logs:/var/log/gitlab \
#   --volume /srv/gitlab/data:/var/opt/gitlab \
#   gitlab/gitlab-ce:latest
# https://qiita.com/Mr-K/items/e0d8f905946703767954
