version: '2'
catalog:
  name: "Zabbix-Stack"
  version: "v1.3.0"
  description: "S.TAKE(KRB/SPG)"
  questions:
    - variable: "OS"
      label: "OS"
      description: "OS"
      type: "string"
      required: true
      default: "centos"
    - variable: "VERSION"
      label: "VERSION"
      description: "VERSION"
      type: "string"
      required: true
      default: "trunk"
    - variable: "HTTP_PORT"
      label: "HTTP_PORT"
      description: "HTTP_PORT"
      type: "int"
      required: true
      default: 11080
    - variable: "ZABBIX_SVR_PORT"
      label: "ZABBIX_SVR_PORT"
      description: "ZABBIX_SVR_PORT"
      type: "int"
      required: true
      default: 10051
    - variable: "DB_NAME"
      label: "DB_NAME"
      description: "DB_NAME"
      type: "string"
      required: true
      default: "zabbix"
    - variable: "DB_USER"
      label: "DB_USER"
      description: "DB_USER"
      type: "string"
      required: true
      default: "zabbix"
    - variable: "DB_USER_PASSWORD"
      label: "DB_USER_PASSWORD"
      description: "DB_USER_PASSWORD"
      type: "string"
      required: true
      default: "zabbix"
    - variable: "DB_ROOT_PASSWORD"
      label: "DB_ROOT_PASSWORD"
      description: "DB_ROOT_PASSWORD"
      type: "string"
      required: true
      default: "zabbix"
    - variable: "TIME_ZONE"
      label: "TIME_ZONE"
      description: "TIME_ZONE"
      type: "string"
      required: true
      default: "Asia/Tokyo"
    - variable: "LOG_LEVEL"
      label: "LOG_LEVEL"
      description: "LOG_LEVEL"
      type: "int"
      required: true
      default: "3"
    - variable: "zabbix_mysql"
      label: "zabbix_mysql"
      description: "zabbix_mysql"
      type: "string"
      required: true
      default: "zabbix_mysql"
    - variable: "zabbix_data"
      label: "zabbix_data"
      description: "zabbix_data"
      type: "string"
      required: true
      default: "zabbix_data"
    - variable: "zabbix_alertscripts"
      label: "zabbix_alertscripts"
      description: "zabbix_alertscripts"
      type: "string"
      required: true
      default: "zabbix_alertscripts"
    - variable: "volume_driver"
      label: "volume_driver"
      description: "volume_driver rancher-nfs"
      type: "string"
      required: true
      default: "rancher-nfs"
    - variable: "PROXYTGT_DB_SERVER_HOST"
      label: "PROXYTGT_DB_SERVER_HOST"
      description: "PROXYTGT_DB_SERVER_HOST"
      type: "string"
      required: true
      default: "some-db-server name or IP"
    - variable: "PROXYTGT_MYSQL_USER"
      label: "PROXYTGT_MYSQL_USER"
      description: "PROXYTGT_MYSQL_USER"
      type: "string"
      required: true
      default: "some-db-server user name"
    - variable: "PROXYTGT_MYSQL_PASSWORD"
      label: "PROXYTGT_MYSQL_PASSWORD"
      description: "PROXYTGT_MYSQL_PASSWORD"
      type: "string"
      required: true
      default: "some-db-server passwd"

services:
  ZabbixDb:
    scale: 1
  ZabbixServer:
    scale: 1
  ZabbixWeb:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 2
      interval: 3000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
  ZabbixAgent:
    scale: 1
  ZabbixMySqlProxy:
    scale: 1
