# Service name must not have '_' in runcher env.
version: '2'
services:

  ZabbixDb:
    # image: mysql:5.7
    # https://hub.docker.com/_/mariadb
    image: mariadb:5.5.64
    hostname: "ZabbixDB"
    tty: true
    stdin_open: true
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${zabbix_mysql}:/var/lib/mysql

  ZabbixServer:
    image: zabbix/zabbix-server-mysql:${OS}-${VERSION}
    hostname: "ZabbixServer"
    tty: true
    stdin_open: true
    environment:
      - DB_SERVER_HOST=ZabbixDb
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - ZBX_DEBUGLEVEL=${LOG_LEVEL}
    # expose:
    #   - "10051"
    ports:
      - "${ZABBIX_SVR_PORT}:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${zabbix_data}:/var/lib/zabbix
      - ${zabbix_alertscripts}:/usr/lib/zabbix/alertscripts
    links:
      - ZabbixDb

  ZabbixWeb:
    image: zabbix/zabbix-web-nginx-mysql:${OS}-${VERSION}
    hostname: "ZabbixWeb"
    tty: true
    stdin_open: true
    environment:
      - ZBX_SERVER_HOST=ZabbixServer
      - DB_SERVER_HOST=ZabbixDb
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - PHP_TZ=${TIME_ZONE}
    # expose:
    #   - "80"
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - ZabbixServer
      - ZabbixDb

# https://github.com/zabbix/zabbix-docker
# https://github.com/psgabriel/docker_zabbix4
# https://github.com/higebu/docker-zabbix-agent-mysql/blob/master/userparameter_mysql.conf

# ZBX_PROXYMODE
# The variable allows to switch Zabbix proxy mode. Bu default, value is 0 - active proxy. Allowed values are 0 - active proxy and 1 - passive proxy.

# ZBX_HOSTNAME
# This variable is unique, case sensitive hostname. By default, value is zabbix-proxy-mysql of the container. It is Hostname parameter in zabbix_proxy.conf.

# ZBX_SERVER_HOST
# This variable is IP or DNS name of Zabbix server or Zabbix proxy. By default, value is zabbix-server. It is Server parameter in zabbix_proxy.conf. It is allowed to specify Zabbix server or Zabbix proxy port number using ZBX_SERVER_PORT variable. It make sense in case of non-default port for active checks.

# ZBX_SERVER_PORT
# This variable is port Zabbix server listening on. By default, value is 10051.

# DB_SERVER_HOST
# This variable is IP or DNS name of MySQL server. By default, value is 'mysql-server'

# DB_SERVER_PORT
# This variable is port of MySQL server. By default, value is '3306'.

# MYSQL_USER, MYSQL_PASSWORD
# These variables are used by Zabbix proxy to connect to Zabbix database. By default, values are zabbix, zabbix.

# MYSQL_DATABASE
# The variable is Zabbix database name. By default, value is zabbix_proxy.

# ZBX_LOADMODULE
# The variable is list of comma separated loadable Zabbix modules. It works with volume /var/lib/zabbix/modules. The syntax of the variable is dummy1.so,dummy2.so.

# ZBX_DEBUGLEVEL
# The variable is used to specify debug level. By default, value is 3. It is DebugLevel parameter in zabbix_server.conf. Allowed values are listed below:

# 0 - basic information about starting and stopping of Zabbix processes;
# 1 - critical information
# 2 - error information
# 3 - warnings
# 4 - for debugging (produces lots of information)
# 5 - extended debugging (produces even more information)
# ZBX_TIMEOUT
# The variable is used to specify timeout for processing checks. By default, value is 4.

# ZBX_JAVAGATEWAY_ENABLE
# The variable enable communication with Zabbix Java Gateway to collect Java related checks. By default, value is false

# ZBX_ENABLEREMOTECOMMANDS=0 # Available since 3.4.0
# ZBX_LOGREMOTECOMMANDS=0 # Available since 3.4.0
# ZBX_HOSTNAMEITEM=system.hostname
# ZBX_SOURCEIP=
# ZBX_PROXYLOCALBUFFER=0
# ZBX_PROXYOFFLINEBUFFER=1
# ZBX_PROXYHEARTBEATFREQUENCY=60
# ZBX_CONFIGFREQUENCY=3600
# ZBX_DATASENDERFREQUENCY=1
# ZBX_STARTPOLLERS=5
# ZBX_IPMIPOLLERS=0
# ZBX_STARTPOLLERSUNREACHABLE=1
# ZBX_STARTTRAPPERS=5
# ZBX_STARTPINGERS=1
# ZBX_STARTDISCOVERERS=1
# ZBX_STARTHTTPPOLLERS=1
# ZBX_JAVAGATEWAY=zabbix-java-gateway
# ZBX_JAVAGATEWAYPORT=10052
# ZBX_STARTJAVAPOLLERS=0
# ZBX_STARTVMWARECOLLECTORS=0
# ZBX_VMWAREFREQUENCY=60
# ZBX_VMWAREPERFFREQUENCY=60
# ZBX_VMWARECACHESIZE=8M
# ZBX_VMWARETIMEOUT=10
# ZBX_ENABLE_SNMP_TRAPS=false
# ZBX_LISTENIP=
# ZBX_HOUSEKEEPINGFREQUENCY=1
# ZBX_CACHESIZE=8M
# ZBX_STARTDBSYNCERS=4
# ZBX_HISTORYCACHESIZE=16M
# ZBX_HISTORYINDEXCACHESIZE=4M
# ZBX_TRAPPERIMEOUT=300
# ZBX_UNREACHABLEPERIOD=45
# ZBX_UNAVAILABLEDELAY=60
# ZBX_UNREACHABLEDELAY=15
# ZBX_LOGSLOWQUERIES=3000
# ZBX_TLSCONNECT=unencrypted
# ZBX_TLSACCEPT=unencrypted
# ZBX_TLSCAFILE=
# ZBX_TLSCRLFILE=
# ZBX_TLSSERVERCERTISSUER=
# ZBX_TLSSERVERCERTSUBJECT=
# ZBX_TLSCERTFILE=
# ZBX_TLSKEYFILE=
# ZBX_TLSPSKIDENTITY=
# ZBX_TLSPSKFILE=

# /usr/lib/zabbix/alertscripts
# The volume is used for custom alert scripts. It is AlertScriptsPath parameter in zabbix_server.conf.

# /usr/lib/zabbix/externalscripts
# The volume is used by External checks (type of items). It is ExternalScripts parameter in zabbix_proxy.conf.

# /var/lib/zabbix/modules
# The volume allows load additional modules and extend Zabbix proxy using LoadModule feature.

# /var/lib/zabbix/enc
# The volume is used to store TLS related files. These file names are specified using ZBX_TLSCAFILE, ZBX_TLSCRLFILE, ZBX_TLSKEY_FILE and ZBX_TLSPSKFILE variables.

# /var/lib/zabbix/ssh_keys
# The volume is used as location of public and private keys for SSH checks and actions. It is SSHKeyLocation parameter in zabbix_proxy.conf.

# /var/lib/zabbix/ssl/certs
# The volume is used as location of of SSL client certificate files for client authentication. It is SSLCertLocation parameter in zabbix_proxy.conf.

# /var/lib/zabbix/ssl/keys
# The volume is used as location of SSL private key files for client authentication. It is SSLKeyLocation parameter in zabbix_proxy.conf.

# /var/lib/zabbix/ssl/ssl_ca
# The volume is used as location of certificate authority (CA) files for SSL server certificate verification. It is SSLCALocation parameter in zabbix_proxy.conf.

# /var/lib/zabbix/snmptraps
# The volume is used as location of snmptraps.log file. It could be shared by zabbix-snmptraps container and inherited using volumes_from Docker option while creating new instance of Zabbix proxy. SNMP traps processing feature could be enabled using shared volume and switched ZBX_ENABLE_SNMP_TRAPS environment variable to true.

# /var/lib/zabbix/mibs
# The volume allows to add new MIB files. It does not support subdirectories, all MIBs must be placed to /var/lib/zabbix/mibs.
