name: DockerRegistry-Stack
description: "Docker Registry, , , "
version: v1.4.0
category: "docker"
maintainer: S.TAKE(KRB/SPG)
license: Apache-2.0
projectURL: https://hub.docker.com/_/registry
# https://github.com/docker/docker-registry
# https://docs.docker.com/registry/deploying/
# https://github.com/docker/distribution
# docker run -d -p 5000:5000 --restart always --name registry registry:2
