# Service name must not have '_' in runcher env.
version: '2'
services:
  proxy:
    image: openresty/openresty:1.13.6.2-2-centos
    stdin_open: true
    volumes:
    - ${openresty_conf}:/opt/store/openresty_conf
    volume_driver: ${volume_driver}
    ports:
    - "${public_http_port}:80"
    - "${public_https_port}:443"
    environment:
    - NGINX_HOST=receipt-ai.bizrobo.com
    - NGINX_PORT=80
    # command: /bin/bash -c "{ /bin/cp -f /opt/store/openresty_data/nginx.conf /usr/local/openresty/nginx/conf/; } && { /bin/cp -rf /opt/store/openresty_data/conf.d/*.conf /etc/nginx/conf.d/; } && exec nginx -g 'daemon off;'"
    labels:
      io.rancher.container.pull_image: always
