name: osTicket-Stack
description: "osTicket 1.x"
version: v1.0.0
category: "helpdesk"
maintainer: S.TAKE(KRB/SPG)
license: MIT
projectURL: https://www.osticket.com
# https://www.bountysource.com/issues/52676699-docker-compose
# https://github.com/CampbellSoftwareSolutions/docker-osticket

# http://52.196.49.70:8888/gitlab/cintake/rancher_catalog.git
# http://ip-172-30-5-227.ap-northeast-1.compute.internal:8888/gitlab/cintake/rancher_catalog.git
# http://devel.bizrobo.com/gitlab/cintake/rancher_catalog

# cf: https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml
