name: OTRS4-Stack
description: "OTRS 4.0.x, mariaDB, postfix"
version: v1.0.0
category: "management"
maintainer: S.TAKE(KRB/SPG)
license: MIT
projectURL: http://www.otrs.jp/
# https://www.slideshare.net/nouphet/20150515-hbstudy-otrs4
# https://github.com/nouphet/otrs-installer/blob/master/get-otrs40-itsm-modules.sh
# http://52.196.49.70:8888/gitlab/cintake/rancher_catalog.git
# http://ip-172-30-5-227.ap-northeast-1.compute.internal:8888/gitlab/cintake/rancher_catalog.git
# http://devel.bizrobo.com/gitlab/cintake/rancher_catalog
