version: '2'
catalog:
  name: "ODOO-Stack"
  version: "v1.0.0"
  description: "S.TAKE(KRB/SPG)"
  questions:
  odoo-web-data:
    - variable: "odoo_web_data"
      label: "odoo_web_data"
      description: "odoo_web_data"
      type: "string"
      required: true
      default: "odoo_web_data"
    - variable: "odoo_web_conf"
      label: "odoo_web_conf"
      description: "odoo_web_conf"
      type: "string"
      required: true
      default: "odoo_web_conf"
    - variable: "odoo_web_addons"
      label: "odoo_web_addons"
      description: "odoo_web_addons"
      type: "string"
      required: true
      default: "odoo_web_addons"
    - variable: "volume_driver"
      label: "volume_driver"
      description: "volume_driver rancher-nfs"
      type: "string"
      required: true
      default: "rancher-nfs"
    - variable: "ext_http_port"
      label: "ext_http_port"
      description: "ext_http_port"
      type: "int"
      required: true
      default: 21080
    - variable: "odoo_db_data"
      label: "odoo_db_data"
      description: "odoo_db_data"
      type: "string"
      required: true
      default: "odoo_db_data"
services:
  web:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8069
      unhealthy_threshold: 2
      interval: 300000
      strategy: recreate
  db:
    scale: 1
  ODOO-lb:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - priority: 1
        protocol: tcp
        service: web
        source_port: ${ext_http_port}
        target_port: 8069
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
