name: NginxPrx
description: "proxy by nginx"
version: v1.0.0
category: "web"
maintainer: S.TAKE(KRB/SPG)
license: MIT
projectURL: http://52.196.49.70:8888/gitlab/cintake/rancher_catalog.git
# http://ip-172-30-5-227.ap-northeast-1.compute.internal:8888/gitlab/cintake/rancher_catalog.git
# http://devel.bizrobo.com/gitlab/cintake/rancher_catalog
