# Service name must not have '_' in runcher env.
version: '2'
services:
  proxy:
    image: nginx
    stdin_open: true
    volumes:
    - ${nginx_data}:/opt/store/nginx
    # :z is invalid for NFS
    # - /opt/store/nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    # - /opt/store/nginx/static/:/opt/store/nginx/static/
    # - /opt/store/nginx/staging/:/opt/store/nginx/staging/
    # - /opt/store/nginx/production/:/opt/store/nginx/production/
    # - /opt/store/nginx/bizrobo.com/dhparam_20190201_1024.pem:/opt/store/nginx/bizrobo.com/dhparam.pem
    # - /opt/store/nginx/bizrobo.com/server.pem:/opt/store/nginx/bizrobo.com/fullchain.pem
    # - /opt/store/nginx/bizrobo.com/key.pem:/opt/store/nginx/bizrobo.com/privkey.pem
    # - /opt/store/nginx/bizrobo.com/chain.pem:/opt/store/nginx/bizrobo.com/chain.pem
    # - /opt/store/nginx/sslip.io/:/opt/store/nginx/sslip.io/
    volume_driver: ${volume_driver}
    ports:
    - "${public_http_port}:80"
    - "${public_https_port}:443"
    environment:
    - NGINX_HOST=receipt-ai.bizrobo.com
    - NGINX_PORT=80
    command: /bin/bash -c "{ /bin/cp -f /opt/store/nginx/conf.d/*.conf /etc/nginx/conf.d/; } && exec nginx -g 'daemon off;'"
    labels:
      io.rancher.container.pull_image: always
