version: '2'
catalog:
  name: "Adminer-Stack"
  version: "v1.0.1"
  description: "S.TAKE(KRB/SPG)"
  questions:
    - variable: "ext_http_port"
      label: "ext_http_port"
      description: "ext_http_port"
      type: "int"
      required: true
      default: 12080
services:
  adminer:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 2
      interval: 3000
      strategy: recreate
