version: '2'
catalog:
  name: "OpenResty"
  version: "v1.6.4"
  description: "S.TAKE(KRB/SPG) add ext_redis_port"
  questions:
    - variable: "openresty"
      label: "openresty"
      description: "openresty"
      type: "string"
      required: true
      default: "openresty-tst"
    - variable: "volume_driver"
      label: "volume_driver"
      description: "volume_driver rancher-nfs"
      type: "string"
      required: true
      default: "rancher-nfs"
    - variable: "ext_http_port"
      label: "ext_http_port"
      description: "ext_http_port(80)"
      type: "int"
      required: true
      default: 21080
    - variable: "ext_https_port"
      label: "ext_https_port"
      description: "ext_https_port(443)"
      type: "int"
      required: true
      default: 21443
    - variable: "openresty_redis_data"
      label: "openresty_redis_data"
      description: "openresty_redis_data"
      type: "string"
      required: true
      default: "openresty_redis_data-tst"
    - variable: "ext_redis_port"
      label: "ext_redis_port"
      description: "ext_redis_port(6379)"
      type: "int"
      required: true
      default: 21379
    - variable: "ext_rediscommander_port"
      label: "ext_rediscommander_port"
      description: "ext_rediscommander_port(81)"
      type: "int"
      required: true
      default: 21081
    - variable: "goaccess_data"
      label: "goaccess_data"
      description: "goaccess_data"
      type: "string"
      required: true
      default: "openresty_goaccess_data-tst"
    - variable: "goaccess_logs"
      label: "goaccess_logs"
      description: "goaccess_logs"
      type: "string"
      required: true
      default: "openresty_goaccess_logs-tst"
    - variable: "goaccess_report"
      label: "goaccess_report"
      description: "goaccess_report"
      type: "string"
      required: true
      default: "openresty_goaccess_report-tst"
    - variable: "ext_goaccess_port"
      label: "ext_goaccess_port"
      description: "ext_goaccess_port(82)"
      type: "int"
      required: true
      default: 21082
services:
  openresty:
    scale: 1
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 80
      unhealthy_threshold: 2
      interval: 300000
      strategy: recreate
  redis:
    scale: 1
  rediscli:
    scale: 1
  redis-commander:
    scale: 1
  goaccess:
    scale: 1
