version: '2'

services:

  registry:
  # docker run -d -p 5000:5000 --restart always --name registry
  # https://docs.docker.com/registry/deploying/
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "${ext_http_port}:5000"
    volumes:
    # -v /mnt/registry:/var/lib/registry
    - ${docker_registry}:/var/lib/registry
    volume_driver: ${volume_driver}
  centos7-dev:
    image: centos:7
    links:
      - registry
    volumes:
    # -v /mnt/registry:/var/lib/registry
    - ${docker_registry_work}:/root
    volume_driver: ${volume_driver}

